Repository KALIIOWORK/basic_python_programs, pull requests merged in 2023-10, with the labels that each got.

#12 Add Number Guessing Game program
  number_guessing_game.py
Labels: hacktoberfest-accepted, hacktoberfest

#16 fix typo on 'How to Contribute' section
  README.md
Labels: documentation

#14 add-temperature-converter
  temperature_converter.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#13 Added Simple Calculator Program
  simple_calculator.py
Labels: hacktoberfest-accepted, hacktoberfest

#26 Add Basic File Manipulation Program
  file_manipulation.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#25 Correct all the typos in readme file
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#17 Fix palindrome checker
  palindrome_checker.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#18 Simple python calculator with square root
  number_guessing_game.py
  simple_calculator_with_squareroot.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#19 Add pattern printer script
  pattern_printer.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#20 Add mini-game feature
  python_mini_game.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#21 Add Word Guessing Game program
  word_guessing_game.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#22 To Do List
  todo_manager.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#24 Add Python calculator script
  calculator.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest
